AllCops:
  TargetRubyVersion: 2.1t
  NewCops: enable
  SuggestExtensions: false

require:
  - rubocop-performance
  - rubocop-thread_safety

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Naming/FileName:
  Exclude:
    - 'lib/omniauth-bigcommerce.rb'
